import load


class Loader:
    wc_lemma_dictionary = None
    important_wc = None
    wp_sequences_svm = None
    question_sequences_svm = None

    def __init__(self, path: str = None):
        """
        Loads and stores multiple files. Is mainly used for passing loaded files.

        Loader.important_wc - if path is not specified it loads dictionary of important word classes generated by method create_important_wc in analysis.py file.
        Loader.wc_lemma_dictionary - loads dictionary where KEY is word and VALUE is tuple word class and word lemma.
                                   - this dictionary was extracted from SYN2015

        Loader.wp_sequences_svm  - sequences for svm (part WP)
        Loader.question_sequences_svm  - sequences for svm (part QUESTION)

        Loader.plus_database_sa, Loader.minus_database_sa - loads database of word for syntax analysis.
        """

        Loader.important_wc = load.load_important_wc() if path is None else load.load_important_wc(path)
        Loader.wc_lemma_dictionary = load.load_wc_lemma_dict()

        # SEQUENCES FOR SVM
        Loader.wp_sequences_svm = load.load_sequences_svm('WP')
        Loader.question_sequences_svm = load.load_sequences_svm('QUESTION')

        # DATABASE FOR SA
        Loader.plus_database_sa, Loader.minus_database_sa = load.load_databases()
